### ISSUE TITLE
Theme only applies to code edtior (not status bar or background of sidebar/tabs)

### ISSUE THREAD

**Issue by JonasGruenwald** [jdinhify/vscode-theme-gruvbox#11]
Not sure if I'm doing something wrong, but unlike on the screenshots here, the theme only applies to the code editor for me, all other colors stay the default light/dark.

I'm setting the theme with the command 'Preferences: Color Theme', do I need to do something else to have it apply globally?

**Comment by jdinhify** [comment]
I'm not sure what's wrong, but let's try to look into this.

Do you have any other extension that's affecting the workbench?

Could you show your full `settings.json` (for both user & workplace) so that I could have a look.

**Comment by JonasGruenwald** [comment]
Hi, thanks for taking the time to reply!

My user settings.json:
```json
{
    "workbench.activityBar.visible": false,
    "workbench.colorTheme": "Gruvbox Dark (Hard)",
    "window.menuBarVisibility": "toggle",
    "editor.minimap.enabled": false,
}
```

The workspace settings are empty.
I just disabled all other extensions and reloaded, no change.

Maybe I should have mentioned: I'm not using the Microsoft binary release of vscode, I am building from source according to their instructions, I just built it from the master of https://github.com/Microsoft/vscode again to make sure I have the latest version, it says version 1.29.0 in the about menu, do you think that could be the issue?

Here is what it looks like for me:
![hqscr_2018-10-30_23-43-05_1920x1080](https://user-images.githubusercontent.com/26603037/47755512-dae22f80-dc9e-11e8-8042-af9e80bd098b.png)
![hqscr_2018-10-30_23-43-11_1920x1080](https://user-images.githubusercontent.com/26603037/47755562-0a913780-dc9f-11e8-82a1-ccb12d96ea23.png)

**Comment by JonasGruenwald** [comment]
Ohh man I feel stupid now, I had installed the wrong one indeed.
Thanks for your work on this extension, looks really good!
