### ISSUE TITLE
`this` keyword don't have highlighting

### ISSUE THREAD

**Issue by Shoizz** [jdinhify/vscode-theme-gruvbox#17]
![image](https://user-images.githubusercontent.com/944858/53496963-cdea1700-3aab-11e9-85e6-2f04612e2ccf.png)
It would be nicer to have it in a different color e.g red or something.

**Comment by jdinhify** [comment]
What programming language is this @Shoizz, and what language syntax highlighting is being displayed as (look at the editor's bottom right)?

This looks like javascript, but I think javascript `this` is already highlighted with a different colour
![screen shot 2019-02-28 at 1 07 37 pm](https://user-images.githubusercontent.com/14046273/53536342-24ae2a00-3b5a-11e9-94ce-dd9a768b0cd7.png)

**Comment by Shoizz** [comment]
@jdinhify Sorry didn't mention it. It's Typescript.

**Comment by jdinhify** [comment]
typescript `this` should now be highlighted with the latest extension version
