### ISSUE TITLE
Peekview keyword has no highlight group.

### ISSUE THREAD

**Issue by ChrisLee63** [jdinhify/vscode-theme-gruvbox#20]
![image](https://user-images.githubusercontent.com/39628662/62290731-a05b2c80-b494-11e9-9c9b-44e74911a5eb.png)
Now it's default ugly red.

**Comment by jdinhify** [comment]
Thanks for reporting this @ppnman 👌
I don't use peekView often though, so not sure what would be the best background, would you be able to suggest a colour?

**Comment by ppnman** [comment]
![image](https://user-images.githubusercontent.com/39628662/62352161-0f3e9100-b53a-11e9-8793-9e72c4c13ed1.png)
What do you think of the color(#ac6913) ?
![image](https://user-images.githubusercontent.com/39628662/62352304-68a6c000-b53a-11e9-9e45-c17773c44b4b.png)
Or this(#23395C)?
Or you can reference other colortheme.
BTW, your gruvbox colorscheme is great, I love it!

**Comment by ppnman** [comment]
BTW, I suggest that the foreground of the item seleceted should be lighter than other entries.
Like this:
(Solarized Dark)
![image](https://user-images.githubusercontent.com/39628662/62352660-45c8db80-b53b-11e9-9332-1c77f747f6a3.png)
Now it is darker than other entries.
(Gruvbox Medium)
![image](https://user-images.githubusercontent.com/39628662/62352723-727cf300-b53b-11e9-816c-5c8ab4cbeede.png)

**Comment by ppnman** [comment]
So the final effect is:
![image](https://user-images.githubusercontent.com/39628662/62353079-588fe000-b53c-11e9-9567-9cec3a68ed2b.png)

```
// PEEK VIEW
    "peekView.border": "#3c3836",
    "peekViewEditor.background": "#3c383650",
    "peekViewEditorGutter.background": "#3c383650",
    "peekViewEditor.matchHighlightBackground": "#ac6913", **#Modified**
    "peekViewResult.background": "#3c383650",
    "peekViewResult.fileForeground": "#ebdbb2",
    "peekViewResult.matchHighlightBackground": "#8ec07c30",
    "peekViewResult.selectionBackground": "#8ec07c30",
    "peekViewResult.selectionForeground": "#FFFFFF", **#Modified**
    "peekViewTitle.background": "#3c383650",
    "peekViewTitleDescription.foreground": "#bdae93",
    "peekViewTitleLabel.foreground": "#ebdbb2",
```

**Comment by jdinhify** [comment]
thanks @ppnman, the color look cool, but I think it's better to stick with the colors in gruvbox palette, would you be able to give the colors.txt a try https://github.com/jdinhify/vscode-theme-gruvbox/blob/master/colors.txt

try 
```
"peekViewEditor.matchHighlightBackground": "#fe801980",
"peekViewResult.selectionForeground": "#fbf1c7"
```

note that you can use 2 chars (00 -> ff) after the color code to specify the alpha, eg. `#fe801980` is the orange 2 in `colors.txt` (`fe8019`) with `80` as alpha

**Comment by ppnman** [comment]
@jdinhify Very good, I like it.
![image](https://user-images.githubusercontent.com/39628662/62436441-3aabc080-b772-11e9-9dbe-a41c5b6536c7.png)

**Comment by jdinhify** [comment]
Thanks @ppnman , would you be able to submit a PR for it? I'm happy to do it if you can't.

It'd be great if you can do for other variants, but no pressure, I can have a follow up commit to address other variants

**Comment by ppnman** [comment]
@jdinhify 
I am really sorry that I just read your response. There are so many things going on there days so that I have no time to browse GitHub.
Of course, I am glad to submit a PR for it. But maybe it takes one week to finish it because I need to consider what color is better in light colorscheme.

**Comment by jdinhify** [comment]
That's alright @ppnman , please take as much time as you need.

Thank you

**Comment by ChrisLee63** [comment]
I am sorry to close the issue because I don't use vscode anymore.
BTW, both the plugin and author are great.
