### ISSUE TITLE
[Minor customization][Help wanted] Selecction color

### ISSUE THREAD

**Issue by nkint** [jdinhify/vscode-theme-gruvbox#21]
Hi!

I love this theme for VSCode but I wanto to change the background selection color (it is the same color of the scrollbar).
See images and the dark blue (`color` selection in the first image and `encodeurl` in the second image):
![image](https://user-images.githubusercontent.com/609314/65672500-7c0d6d80-e049-11e9-998f-88292201b389.png)
![image](https://user-images.githubusercontent.com/609314/65672598-97787880-e049-11e9-97f4-e76766f5112a.png)

As far as I can understand using the built-in Mac-OS/X `Digital Colour Meter` the color code is: #18222D
But I'm not sure how to change it or where to find it in this repository.

Thanks in advance and sorry if I bother you!

VSCode Version: 1.38.1
OS: Darwin x64 18.2.0

**Comment by jdinhify** [comment]
Thanks @nkint , there should be some tokens to set it. I'll have a look later.

This one is probably similar to the other issue https://github.com/jdinhify/vscode-theme-gruvbox/issues/20#issuecomment-518070753

**Comment by jdinhify** [comment]
Also @nkint , could you please check if you're using the right extension (it does look like you're using a different one in your screenshot)? My editor is showing different colour:

<img width="315" alt="Screen Shot 2019-09-30 at 3 47 21 pm" src="https://user-images.githubusercontent.com/14046273/65852544-cc623380-e399-11e9-9560-0773bddba8d1.png">

The extension of this repo is https://marketplace.visualstudio.com/items?itemName=jdinhlife.gruvbox

**Comment by nkint** [comment]
Ok thanks, resolved!
