### ISSUE TITLE
Publish extensions to open-vsx

### ISSUE THREAD

**Issue by erenhatirnaz** [jdinhify/vscode-theme-gruvbox#27]
I'm a [VS Codium](https://github.com/VSCodium/vscodium) user, a FLOSS version of VS Code, it's the same code but without the Microsoft's telemetry and branding.
I want to request if possible to add the _Gruvbox Theme_ extension on the [open-vsx.org](https://open-vsx.org/) market to us doesn't need to works with the Microsoft marketplace as is unclear if it's legal to use it on VS Code forks, see [here](https://github.com/microsoft/vscode/issues/31168).
 
Additional info:
* This is [how to](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) publish a new extension.

**Comment by jdinhify** [comment]
Thanks @erenhatirnaz 
I'm happy to publish the theme to open-vsx.org. Is there anything I need to be aware of, such as licensing, ownership, etc...?

I'm not familiar with the market so it will take some time to set up

**Comment by erenhatirnaz** [comment]
I'm not quite sure, but you may need to add [a FLOSS license](https://www.gnu.org/licenses/license-list.html). Perhaps this page will help you about ownership: https://github.com/eclipse/openvsx/wiki/Namespace-Access.

**Comment by jdinhify** [comment]
Thanks @erenhatirnaz , this has now been published on open-vsx https://open-vsx.org/extension/jdinhlife/gruvbox
