### ISSUE TITLE
JavaScript syntax highlighting color improvements

### ISSUE THREAD

**Issue by dziku86** [jdinhify/vscode-theme-gruvbox#30]
Language: **JavaScript**
<br>
**It would be super nice to color-wise distinguish things like:**

Syntax to improve | E.g., API | E.g., Screenshot
--|-|-
 `variable`.`property ` |  `Node.parentElement` | ![image](https://user-images.githubusercontent.com/56586404/103682452-339d6900-4f89-11eb-8e2b-34ff80ff09ac.png)
`variable`.`property`.`string` | `HTMLOrForeignElement.dataset.DOMStringMap` | ![image](https://user-images.githubusercontent.com/56586404/103684050-4618a200-4f8b-11eb-8ea0-6a3b2d45b5fc.png)
 `variable`.`property`.`property` | `ElementCSSInlineStyle.style.property` | ![image](https://user-images.githubusercontent.com/56586404/103683645-becb2e80-4f8a-11eb-9d08-cf35a952d18e.png)
 `interface`.`property`.`property` | `Document.documentElement.property` | ![image](https://user-images.githubusercontent.com/56586404/103684992-becc2e00-4f8c-11eb-82c1-69f93ed67464.png)
`parameter`=>`variable`.`property` | *Arrow function expressions* | ![image](https://user-images.githubusercontent.com/56586404/103689138-300edf80-4f93-11eb-85bb-e63d3e870a3e.png)
<br>
I hope this clearly represents what I mean. ¯\\\_(ツ)_/¯

**Comment by jdinhify** [comment]
Thanks @dziku86 , I think I get what you meant. However, there's a few issues that we might need to think more about:

1. The syntax highlighting of vscode doesn't seem to provide much difference between stuff like `variable`.`property`.`string` in your suggestion. Or at least I haven't been able to get any difference using some of the sample codes that I have. Note that we're relying on the `Editor Tokens and Scopes` to be able to tell vscode what/how to highlight. You can check it out yourself by using the command `Developer: Inspect Editor Tokens and Scopes` (pressing Cmd + Shift + P on OSX).
2. We only have limited colours to use (technically we can introduce more colours but it won't be gruvbox anymore), it might not be possible to use unique colour for each level
3. We're only talking about 2-3 level depth, what about deeper objects? We could get the same problem as no.2, and potentially confuse users with having too much colours

I checked some of the more popular themes and they don't seem to support those as well.
Maybe I just misinterpret your suggestions, perhaps having some code examples that we can use & discuss would be easier?

**Comment by dziku86** [comment]
@jdinhify thank you for breaking this down. Sadly I was expecting that this can't be done (easily).
My main objective is to **distinguish user defined code (variables, etc.) and programming language syntax**.
Even *italic font style* would be sufficient to achieve this goal.
