### ISSUE TITLE
Publish the theme in Open VSX Registry

### ISSUE THREAD

**Issue by jeffteixeira** [jdinhify/vscode-theme-gruvbox#31]
This theme can only be installed on VSCode. In Code-OSS and VSCodium, when searching in the extensions tab, it does not appear. Publishing it on [Open VSX Registry](https://open-vsx.org), it would be possible to install it on VSCodium and Code-OSS.

**Comment by jdinhify** [comment]
Thanks @jeffteixeira , this has now been published on open-vsx https://open-vsx.org/extension/jdinhlife/gruvbox

**Comment by jeffteixeira** [comment]
Thanks @jdinhify :)
