### ISSUE TITLE
Does the font displayed come with it or do we have to manually download it?

### ISSUE THREAD

**Issue by hk-32** [jdinhify/vscode-theme-gruvbox#32]
Hey, sorry lol I know issues isn't the best place to ask questions but just wanted to know what the name of the font displayed in the images is called.

https://raw.githubusercontent.com/jdinhify/vscode-theme-gruvbox/master/images/screenshots.jpg

**Comment by jdinhify** [comment]
Hey @hk-32 

I'm not using that font anymore, but if I remember correctly, it should be Inconsolata: https://fonts.google.com/specimen/Inconsolata

I'm now trying out another font called MonoLisa (https://www.monolisa.dev/) if you're interested
