### ISSUE TITLE
Scrollbar suggestion

### ISSUE THREAD

**Issue by zer09** [jdinhify/vscode-theme-gruvbox#4]
Add more contrast on scrollbar "bar" when the mouse is hovered on the scrollbar area.
Because you cant "barely" see the scrollbar unless you hit the exact position of it.

Thanks.

**Comment by jdinhlife** [comment]
Currently, when you hover over the small bar, it'll be highlighted. I'm thinking what you're suggesting is doing the same when hovering over the whole scrollbar area?

**Comment by zer09** [comment]
Yeah, you're right. Sometimes on a long documents, I can't spot the small bar easily.

**Comment by jdinhify** [comment]
Cool, I just had a look and there's no option to change the slider on hovering over the whole scrollbar area.
However, I agree with what you suggest though, making that a bit more visible would be helpful, so I'll make the default slider background brighter regardless of whether it's being hovered over or not, hope that would help.

**Comment by zer09** [comment]
Thanks, I will appreciate that so much. Actually I tried many themes just because of that, but I am still coming back to your theme.

**Comment by jdinhify** [comment]
Thanks, I didn't need to use the scrollbar much to realise the issue.

Anyway, the change is done in 0e1691d.

Your vscode should be able to update the extension now. Please try it and let me know what you think

**Comment by zer09** [comment]
WOW that's quick. I already update it, and I like it.

Thank you so much.
