### ISSUE TITLE
Contrast on bottom bar in light mode 

### ISSUE THREAD

**Issue by pattrickrice** [jdinhify/vscode-theme-gruvbox#41]
Pretty much all variants do black text on dark grey which is pretty frustrating to try to read

<img width="1392" alt="Screen Shot 2021-08-27 at 9 22 04 AM" src="https://user-images.githubusercontent.com/20763171/131159536-6352ab87-9054-40fd-bcde-57e3e52de44b.png">

Compare to Light (Visual Studio) theme
<img width="1220" alt="Screen Shot 2021-08-27 at 9 32 18 AM" src="https://user-images.githubusercontent.com/20763171/131159790-39607808-110f-4329-9b80-93fdaeab9ee1.png">

**Comment by jdinhify** [comment]
Hi @pattrickrice 

The status bar should have the theme's colours, please see screenshot for mine

<img width="1280" alt="vscode-status-bar" src="https://user-images.githubusercontent.com/14046273/132096708-950be3ad-05cf-43d2-8fdd-668479aaf1c6.png">

Could you please confirm that you're using the correct theme as there's a few gruvbox ones in the marketplace. The theme from this repo is https://marketplace.visualstudio.com/items?itemName=jdinhlife.gruvbox

Perhaps some more information in case we need to debug, such as your vscode version (stable/insiders), your OS (windows/macos/linux/...)

**Comment by pattrickrice** [comment]
Well, I don't know how it got set, but I found this setting in my user settings that turned out to be the fault. Apologies for the false report! 

```json
    "workbench.colorCustomizations": {
        "statusBar.background": "#767676"
    },
```
