### ISSUE TITLE
Any plans for a light version?

### ISSUE THREAD

**Issue by josebalius** [jdinhify/vscode-theme-gruvbox#6]
Are there any plans to do a light version?

**Comment by jdinhify** [comment]
Thanks Jose. I did have different versions in mind, but never got time around to try the light version and make one variant for it. Also I'm not using light version full time so I might not be the best one to implement it.
The thing I had in mind was just replacing the dark colors with their corresponding light colors and hope it'll turn out alright.

Perhaps I can draft up something on the weekend and see how it goes. I'm assuming you're talking about a `medium` contrast theme? I'll want to make a proper one first, then the other variants will just be replacing the background colors

**Comment by jdinhify** [comment]
New version published with my rough draft of light versions. Please try them and let me know if there's any suggestion, or if you want to contribute.

Thank you!

**Comment by josebalius** [comment]
@jdinhify I will take it for a spin this week, thank you!!!

**Comment by josebalius** [comment]
@jdinhify So far it looks perfect, thank you again. Noticed that its missing the background color for non-selected tabs.

Here is a screenshot, I can submit a PR but not sure which setting in vscode controls this:

<img width="439" alt="screen shot 2018-02-05 at 9 50 49 am" src="https://user-images.githubusercontent.com/339080/35810740-b373c484-0a5a-11e8-9337-f7a9e07c5ebb.png">

**Comment by jdinhify** [comment]
Thanks @josebalius , I noticed that too but wasn't sure which setting either, I'll have a look into vscode doco and fix it when I have time. But of course, if you found the setting and could submit a PR, it'd be great.
