### ISSUE TITLE
Italic for params

### ISSUE THREAD

**Issue by im-n1** [jdinhify/vscode-theme-gruvbox#7]
Hi,

I'm here to contribute...sort of :) I would like to add a feature from my previous theme - params being written by italics style.

Here is the code which does thie trick in theme json file.

```javascript
{
	"scope": [
		"entity.name.variable.parameter",
		"meta.at-rule.function variable",
		"meta.at-rule.mixin variable",
		"meta.function.arguments variable.other.php",
		"meta.selectionset.graphql meta.arguments.graphql variable.arguments.graphql",
		"variable.parameter"
	],
	"settings": {
		"foreground": "#83a598",
		"fontStyle": "italic"
	}
},
```

The think is I would like to put a new directive to settings to enable that feature. Something like `gruvbox.params.italics = true`. But I have no idea how to do that.

Any ideas? Is that even possible?

**Comment by jdinhify** [comment]
It's a great idea. I don't know if it's possible, but when I have time, I'll look into it.

Thanks for the idea @grafa

**Comment by jdinhify** [comment]
There's an open issue with vscode on this https://github.com/Microsoft/vscode/issues/32579, doesn't look like there's a font configuration option for now. We can only do that using user settings or (possibly) duplicate the font with variants (eg. Gruvbox Dark Medium - italic, bold, etc...) but it's not really ideal considering this has 6 color variants already. I'll keep an eye on the issue on vscode and see if we can have something in the future

**Comment by jdinhify** [comment]
Closing this as there's no config option & it's not ideal to duplicate variants further
