### ISSUE TITLE
Improve inlayHints colors

### ISSUE THREAD

**Issue by shenghui0779** [jdinhify/vscode-theme-gruvbox#73]
- Theme `Gruvbox Light`
<img width="411" alt="image" src="https://user-images.githubusercontent.com/67535398/210746030-ca349e14-7dfd-4e2e-9255-f6e7cec0dd4e.png">

- Theme `Atom One Light`
<img width="411" alt="image" src="https://user-images.githubusercontent.com/67535398/210745819-2d7480f6-6167-4472-bd9f-c82c3d06214a.png">

**Comment by shenghui0779** [comment]
- Theme `Gruvbox Light`
<img width="411" alt="image" src="https://user-images.githubusercontent.com/67535398/210746030-ca349e14-7dfd-4e2e-9255-f6e7cec0dd4e.png">

- Theme `Atom One Light`
<img width="411" alt="image" src="https://user-images.githubusercontent.com/67535398/210745819-2d7480f6-6167-4472-bd9f-c82c3d06214a.png">

**Comment by shenghui0779** [comment]
This is my custom color:

```json
{
    "workbench.colorCustomizations": {
        "[Gruvbox Light Hard]": {
            "editorInlayHint.foreground": "#999999",
            "editorInlayHint.background": "#f9f5d7"
        }
    }
}
```

<img width="412" alt="image" src="https://user-images.githubusercontent.com/67535398/210917324-6abcdd14-c2a9-41cc-a2c7-ab5f61e40810.png">

**Comment by pattrickrice** [comment]
@shenghui0779 what file did you put that customization in? Tried my User Settings and it didn't work
