### ISSUE TITLE
Integrated terminal border not visible

### ISSUE THREAD

**Issue by subhammridha** [jdinhify/vscode-theme-gruvbox#8]
Thank you for porting the gruvbox theme to vs code. 

One problem with this theme is that the integrated terminal top border is not shown. This is causing heavy confusion while typing since I am unable to understand whether terminal is open on top a file when suddenly switching to vscode (,say, from a browser). 

If possible, kindly rectify this.

**Comment by jdinhify** [comment]
Sure, I don't use built-in terminal much so didn't notice the issue. Will put in something quickly

**Comment by jdinhify** [comment]
This is included in the latest release
