### ISSUE TITLE
vue custom component tag highlight

### ISSUE THREAD

**Issue by Arifisar** [jdinhify/vscode-theme-gruvbox#93]
Is there a way to enable this feature?
gruvbox
![image](https://github.com/jdinhify/vscode-theme-gruvbox/assets/66297144/a4a32f0d-5fb3-42da-b867-c723cb9a27d3)
one dark pro
![image](https://github.com/jdinhify/vscode-theme-gruvbox/assets/66297144/f1230841-ee46-4d2f-b991-8520ded34ee1)

**Comment by MrTj458** [comment]
I just made pull request #95 for this.
