### ISSUE TITLE
Custom background color

### ISSUE THREAD

**Issue by itacud95** [jdinhify/vscode-theme-gruvbox#94]
Hello, is it possible to change the background color of the theme? 

I would like to change the background color to `#000`. Is there a setting somewhere I can change this? 

I know that you can set/override the theme colors in `settings.json` with `"editor.background": "#000"` and so on, but it would be nice if there was a option setting this using a setting for this theme. 

Is there any such options? 

Thanks.

**Comment by itacud95** [comment]
The following settings seems to achieve the same, if to any help
```
{
    "workbench.colorCustomizations": {
        "editor.background": "#000",
        "tab.activeBackground": "#000",
        "tab.inactiveBackground": "#000",
        "statusBar.background": "#000",
        "sideBar.background": "#000",
        "activityBar.background": "#000",
        "titleBar.activeBackground": "#000",
    },
}
```

**Comment by jdinhify** [comment]
maybe this would be possible if this gets implemented https://github.com/microsoft/vscode/issues/105247, however, it seems there's no intention to do so

so I don't think we'll be able to have such option, I would recommend keep what you have

closing since there's nothing can be done
